services:
  termix:
    image: ghcr.io/lukegus/termix:release-1.11.0
    container_name: termix
    restart: unless-stopped
    user: 1000:1000
    networks:
      - traefik_proxy
    volumes:
      - /var/docker/termix:/app/data
    labels:
      traefik.enable: true
      traefik.http.services.termix.loadbalancer.server.port: 8080
      traefik.http.routers.termix.entrypoints: websecure
      traefik.http.routers.termix.tls: true
      homepage.group: Monitoring & Management
      homepage.name: Termix
      homepage.icon: termix.svg
      homepage.href: https://${TERMIX_URL}
      homepage.description: All-in-one server management platform
      homepage.showStats: false

networks:
  traefik_proxy:
    external: true
