name: ghostfolio
services:
  ghostfolio:
    image: docker.io/ghostfolio/ghostfolio:2.234.0
    container_name: ghostfolio
    restart: unless-stopped
    networks:
      - traefik_proxy
      - ghostfolio
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3333/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      traefik.enable: true
      traefik.http.routers.ghostfolio.tls: true
      traefik.http.routers.ghostfolio.entrypoints: websecure
      traefik.http.services.ghostfolio.loadbalancer.server.port: 3333
      homepage.group: Finances & Wealth Management
      homepage.name: Ghostfolio
      homepage.icon: ghostfolio.svg
      homepage.href: https://${GHOSTFOLIO_URL}
      homepage.description: Open source wealth management software
      homepage.showStats: false

  postgres:
    image: docker.io/library/postgres:15-alpine
    container_name: gf-postgres
    restart: unless-stopped
    networks:
      - ghostfolio
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    healthcheck:
      test:
        ["CMD-SHELL", 'pg_isready -d "$${POSTGRES_DB}" -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/docker/ghostfolio:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    container_name: gf-redis
    restart: unless-stopped
    user: 999:1000
    networks:
      - ghostfolio
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    healthcheck:
      test:
        ["CMD-SHELL", 'redis-cli --pass "$${REDIS_PASSWORD}" ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  traefik_proxy:
    external: true
  ghostfolio:
