---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: Homeserver
headerStyle: clean
statusStyle: "dot"
showStats: true

layout:
  DNS & Router:
    style: row
    columns: 2
  Monitoring & Management:
    style: row
    columns: 4
  Account Management:
    style: row
    columns: 2
  Finances & Wealth Management:
    style: row
    columns: 2
  Cloud & Storage:
  Media & Streaming:
  Download:
  Tools:
    style: row
    columns: 3
  Games & Game Tools:
    style: row
    columns: 3

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: false
